# Generated by Django 3.2 on 2021-07-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210721_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_girl',
            field=models.BooleanField(default=False, verbose_name='君は女の子？'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_men',
            field=models.BooleanField(default=True, verbose_name='君は男の子？'),
        ),
    ]
