# Generated by Django 3.2 on 2021-05-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoupleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
            ],
        ),
        migrations.CreateModel(
            name='GirlMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girl_mail', models.EmailField(max_length=100, verbose_name='彼女のメールアドレス')),
                ('girl_nickname', models.CharField(max_length=10, verbose_name='彼女のニックネーム')),
                ('couple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.couplemaster', verbose_name='カップルID')),
            ],
        ),
        migrations.CreateModel(
            name='MenMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_mail', models.EmailField(max_length=100, verbose_name='彼氏のメールアドレス')),
                ('men_nickname', models.CharField(max_length=10, verbose_name='彼氏のニックネーム')),
                ('couple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.couplemaster', verbose_name='カップルID')),
            ],
        ),
        migrations.CreateModel(
            name='OmoideTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('couple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.couplemaster')),
            ],
        ),
        migrations.CreateModel(
            name='MenTextTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttime', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('text', models.TextField(verbose_name='本文')),
                ('men_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.menmaster')),
                ('omoide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.omoidetran')),
            ],
        ),
        migrations.CreateModel(
            name='GirlTextTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttime', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('text', models.TextField(verbose_name='本文')),
                ('girl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.girlmaster')),
                ('omoide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.omoidetran')),
            ],
        ),
    ]
