# Generated by Django 3.2 on 2021-07-25 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couplemaster',
            name='girl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='girl_instance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couplemaster',
            name='men_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_instance', to=settings.AUTH_USER_MODEL),
        ),
    ]
