# Generated by Django 3.2 on 2021-05-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210518_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttran',
            name='girl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.girlmaster'),
        ),
        migrations.AlterField(
            model_name='texttran',
            name='men_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.menmaster'),
        ),
    ]
