# Generated by Django 3.2 on 2021-06-28 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_omoidetran_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttran',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='texttran',
            name='text',
            field=models.TextField(verbose_name='コメント'),
        ),
    ]
