# Generated by Django 3.2 on 2021-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210629_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttran',
            name='text',
            field=models.TextField(null=True, verbose_name='コメント'),
        ),
    ]
