# Generated by Django 3.2 on 2021-06-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_texttran_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttran',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
