# Generated by Django 3.2 on 2021-06-29 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_texttran_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='omoidetran',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='サムネイル'),
        ),
    ]
