# Generated by Django 3.2 on 2021-06-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_omoidetran_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omoidetran',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
