# Generated by Django 3.2 on 2021-07-01 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_thumnail_omoidetran_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omoidetran',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='サムネイル'),
        ),
    ]
